export { default as WorldManager } from './WorldManager'
export { getBiomeComponent } from './BiomeRegistry'
export { default as Tile } from './Tile'
export { TILE_SIZE, RENDER_DISTANCE, BIOME_WEIGHTS, type BiomeType } from './types'
export { default as ForestTile } from './biomes/ForestTile'
export { default as StreamTile } from './biomes/StreamTile'
export { default as RockyTile } from './biomes/RockyTile'
export { default as HillsTile } from './biomes/HillsTile'
export { default as PathTile } from './biomes/PathTile'